# Generated by Django 5.2.18 on 2026-10-08 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="عنوان اصلی")),
                (
                    "title_fa",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="عنوان فارسی"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="توضیح اصلی"),
                ),
                (
                    "description_fa",
                    models.TextField(blank=True, verbose_name="توضیح فارسی"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("concert", "کنسرت"),
                            ("theatre", "تئاتر و نمایش"),
                            ("art_exhibition", "نمایشگاه هنری"),
                            ("museum_culture", "موزه و رویداد فرهنگی"),
                            ("film_festival", "جشنواره\u200cی فیلم"),
                            ("art_workshop", "ورکشاپ هنری"),
                            ("sports", "رویداد ورزشی"),
                            ("city_festival", "جشنواره\u200cی شهری"),
                            ("municipality", "برنامه\u200cی شهرداری"),
                            ("tour", "تور"),
                        ],
                        max_length=30,
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
                ("start", models.DateTimeField(verbose_name="شروع")),
                (
                    "end",
                    models.DateTimeField(blank=True, null=True, verbose_name="پایان"),
                ),
                (
                    "price_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="حداقل قیمت",
                    ),
                ),
                (
                    "price_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="حداکثر قیمت",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="TRY", max_length=3, verbose_name="واحد پول"
                    ),
                ),
                ("is_free", models.BooleanField(default=False, verbose_name="رایگان")),
                (
                    "ticket_url",
                    models.URLField(
                        blank=True, max_length=1000, verbose_name="لینک بلیت"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, max_length=1000, verbose_name="تصویر"),
                ),
                (
                    "source_url",
                    models.URLField(
                        max_length=1000, unique=True, verbose_name="لینک منبع"
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="اولین بار دیده شده"
                    ),
                ),
                (
                    "last_checked",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین بررسی"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین تغییر"
                    ),
                ),
                ("confidence", models.FloatField(default=0, verbose_name="اطمینان AI")),
                (
                    "content_hash",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="هش محتوا"
                    ),
                ),
                (
                    "review_reason",
                    models.TextField(blank=True, verbose_name="دلیل بررسی دستی"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("published", "منتشر شده"),
                            ("needs_review", "در صف بررسی"),
                            ("rejected", "رد شده"),
                        ],
                        db_index=True,
                        default="needs_review",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="core.city",
                        verbose_name="شهر",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="core.district",
                        verbose_name="محله",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="sources.source",
                        verbose_name="منبع",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="core.venue",
                        verbose_name="مکان",
                    ),
                ),
            ],
            options={
                "verbose_name": "رویداد",
                "verbose_name_plural": "رویدادها",
                "ordering": ["start"],
            },
        ),
        migrations.CreateModel(
            name="EventChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field", models.CharField(max_length=30, verbose_name="فیلد")),
                (
                    "old_value",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="مقدار قبلی"
                    ),
                ),
                (
                    "new_value",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="مقدار جدید"
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان تغییر"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="events.event",
                        verbose_name="رویداد",
                    ),
                ),
            ],
            options={
                "verbose_name": "تغییر رویداد",
                "verbose_name_plural": "تاریخچه\u200cی تغییرات",
                "ordering": ["-changed_at"],
            },
        ),
    ]
