# Generated by Django 5.2.18 on 2026-10-08 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="duplicate_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicates",
                to="events.event",
                verbose_name="تکراریِ رویداد",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "منتشر شده"),
                    ("needs_review", "در صف بررسی"),
                    ("rejected", "رد شده"),
                    ("duplicate", "تکراری"),
                ],
                db_index=True,
                default="needs_review",
                max_length=20,
                verbose_name="وضعیت",
            ),
        ),
    ]
