# Generated by Django 5.2.18 on 2026-10-08 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_dedup"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewQueueEvent",
            fields=[],
            options={
                "verbose_name": "رویداد در صف بررسی",
                "verbose_name_plural": "صف بررسی دستی",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("events.event",),
        ),
    ]
