# Generated by Django 5.2.18 on 2026-10-08 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="نام (ترکی/انگلیسی)"
                    ),
                ),
                ("name_fa", models.CharField(max_length=100, verbose_name="نام فارسی")),
                ("slug", models.SlugField(unique=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "شهر",
                "verbose_name_plural": "شهرها",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "name_fa",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="نام فارسی"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districts",
                        to="core.city",
                        verbose_name="شهر",
                    ),
                ),
            ],
            options={
                "verbose_name": "محله",
                "verbose_name_plural": "محله\u200cها",
                "ordering": ["city", "name"],
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام")),
                (
                    "address",
                    models.CharField(blank=True, max_length=500, verbose_name="آدرس"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venues",
                        to="core.city",
                        verbose_name="شهر",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="venues",
                        to="core.district",
                        verbose_name="محله",
                    ),
                ),
            ],
            options={
                "verbose_name": "مکان",
                "verbose_name_plural": "مکان\u200cها",
                "ordering": ["name"],
            },
        ),
        migrations.AddConstraint(
            model_name="district",
            constraint=models.UniqueConstraint(
                fields=("city", "name"), name="unique_district_per_city"
            ),
        ),
        migrations.AddConstraint(
            model_name="venue",
            constraint=models.UniqueConstraint(
                fields=("city", "name"), name="unique_venue_per_city"
            ),
        ),
    ]
