# Generated by Django 5.2.18 on 2026-10-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("view", "بازدید"), ("whatsapp", "کلیک واتساپ")],
                        max_length=20,
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        help_text="event / tour / university", max_length=20
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "visitor_id",
                    models.CharField(
                        db_index=True, max_length=36, verbose_name="شناسه\u200cی ناشناس"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "بازدید/کلیک",
                "verbose_name_plural": "بازدیدها و کلیک\u200cها",
                "ordering": ["-created_at"],
            },
        ),
    ]
