# Generated by Django 5.2.18 on 2026-10-08 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_interaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام آژانس")),
                (
                    "license_number",
                    models.CharField(max_length=100, verbose_name="شماره\u200cی مجوز"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="یادداشت")),
            ],
            options={
                "verbose_name": "آژانس",
                "verbose_name_plural": "آژانس\u200cها",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("guided", "تور با آژانس"),
                            ("self_guided", "تور خودگردان"),
                        ],
                        default="guided",
                        max_length=20,
                        verbose_name="نوع",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="عنوان")),
                ("description", models.TextField(blank=True, verbose_name="توضیح")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="قیمت",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="TRY", max_length=3, verbose_name="واحد پول"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ظرفیت"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, max_length=1000, verbose_name="تصویر"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="منتشر شود"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tours",
                        to="tours.agency",
                        verbose_name="آژانس برگزارکننده",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tours",
                        to="core.city",
                        verbose_name="شهر",
                    ),
                ),
            ],
            options={
                "verbose_name": "تور",
                "verbose_name_plural": "تورها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TourDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاریخ شروع")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ پایان"),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dates",
                        to="tours.tour",
                        verbose_name="تور",
                    ),
                ),
            ],
            options={
                "verbose_name": "تاریخ تور",
                "verbose_name_plural": "تاریخ\u200cهای تور",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="TourStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1, verbose_name="ترتیب")),
                ("name", models.CharField(max_length=300, verbose_name="نام ایستگاه")),
                ("description", models.TextField(blank=True, verbose_name="توضیح")),
                (
                    "opening_hours",
                    models.CharField(
                        blank=True,
                        help_text="مثلاً 09:00–17:00",
                        max_length=200,
                        verbose_name="ساعت کاری",
                    ),
                ),
                (
                    "closed_days",
                    models.CharField(
                        blank=True,
                        help_text="مثلاً دوشنبه\u200cها",
                        max_length=200,
                        verbose_name="روزهای تعطیل",
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="tours.tour",
                        verbose_name="تور",
                    ),
                ),
            ],
            options={
                "verbose_name": "ایستگاه",
                "verbose_name_plural": "ایستگاه\u200cها",
                "ordering": ["tour", "order"],
            },
        ),
    ]
