# Generated by Django 5.2.18 on 2026-10-08 09:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان"),
                ),
                ("model", models.CharField(max_length=100, verbose_name="مدل")),
                (
                    "purpose",
                    models.CharField(
                        choices=[("extraction", "استخراج"), ("translation", "ترجمه")],
                        max_length=20,
                        verbose_name="کاربرد",
                    ),
                ),
                ("is_batch", models.BooleanField(default=False, verbose_name="Batch")),
                (
                    "input_tokens",
                    models.PositiveIntegerField(default=0, verbose_name="توکن ورودی"),
                ),
                (
                    "output_tokens",
                    models.PositiveIntegerField(default=0, verbose_name="توکن خروجی"),
                ),
                (
                    "cost_usd",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=10,
                        verbose_name="هزینه (دلار)",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(blank=True, max_length=1000, verbose_name="صفحه"),
                ),
            ],
            options={
                "verbose_name": "مصرف API",
                "verbose_name_plural": "مصرف API",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام")),
                (
                    "adapter",
                    models.SlugField(
                        help_text="نام فایل adapter در پوشه\u200cی sources/adapters",
                        unique=True,
                        verbose_name="کد adapter",
                    ),
                ),
                ("url", models.URLField(verbose_name="آدرس")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("events", "رویداد"),
                            ("venues", "مکان"),
                            ("university", "دانشگاه"),
                        ],
                        default="events",
                        max_length=20,
                        verbose_name="نوع",
                    ),
                ),
                (
                    "access_method",
                    models.CharField(
                        choices=[
                            ("api", "API"),
                            ("rss", "RSS"),
                            ("open_data", "داده\u200cی باز"),
                            ("crawler", "خزنده (crawler)"),
                        ],
                        max_length=20,
                        verbose_name="روش دسترسی",
                    ),
                ),
                (
                    "check_frequency",
                    models.DurationField(
                        default=datetime.timedelta(days=1),
                        verbose_name="فاصله\u200cی بررسی",
                    ),
                ),
                (
                    "terms_status",
                    models.CharField(
                        choices=[
                            ("allowed", "مجاز"),
                            ("needs_partnership", "نیاز به همکاری رسمی"),
                            ("forbidden", "ممنوع"),
                        ],
                        default="allowed",
                        max_length=20,
                        verbose_name="وضعیت قوانین سایت",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین اجرا"
                    ),
                ),
                (
                    "last_success",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین اجرای موفق"
                    ),
                ),
                (
                    "items_found_last_run",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="تعداد پیدا شده در آخرین اجرا",
                    ),
                ),
                ("last_error", models.TextField(blank=True, verbose_name="آخرین خطا")),
                ("notes", models.TextField(blank=True, verbose_name="یادداشت")),
            ],
            options={
                "verbose_name": "منبع",
                "verbose_name_plural": "منابع",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PageSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        max_length=1000, unique=True, verbose_name="آدرس صفحه"
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(max_length=64, verbose_name="هش محتوا"),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="اولین بار دیده شده"
                    ),
                ),
                ("last_checked", models.DateTimeField(verbose_name="آخرین بررسی")),
                ("last_changed", models.DateTimeField(verbose_name="آخرین تغییر")),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="sources.source",
                        verbose_name="منبع",
                    ),
                ),
            ],
            options={
                "verbose_name": "صفحه\u200cی بررسی\u200cشده",
                "verbose_name_plural": "صفحه\u200cهای بررسی\u200cشده",
            },
        ),
        migrations.CreateModel(
            name="SourceRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="شروع"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="پایان"),
                ),
                (
                    "links_found",
                    models.PositiveIntegerField(
                        default=0, verbose_name="لینک\u200cهای پیدا شده"
                    ),
                ),
                (
                    "unchanged",
                    models.PositiveIntegerField(default=0, verbose_name="بدون تغییر"),
                ),
                (
                    "created",
                    models.PositiveIntegerField(default=0, verbose_name="جدید"),
                ),
                (
                    "updated",
                    models.PositiveIntegerField(
                        default=0, verbose_name="به\u200cروز شده"
                    ),
                ),
                (
                    "sent_to_review",
                    models.PositiveIntegerField(default=0, verbose_name="به صف بررسی"),
                ),
                (
                    "failed",
                    models.PositiveIntegerField(default=0, verbose_name="ناموفق"),
                ),
                ("error", models.TextField(blank=True, verbose_name="خطا")),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="sources.source",
                        verbose_name="منبع",
                    ),
                ),
            ],
            options={
                "verbose_name": "اجرای منبع",
                "verbose_name_plural": "اجراهای منابع",
                "ordering": ["-started_at"],
            },
        ),
    ]
