# Generated by Django 5.2.18 on 2026-10-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0003_activate_sehir_tiyatrolari"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcerun",
            name="duplicates",
            field=models.PositiveIntegerField(default=0, verbose_name="تکراری"),
        ),
    ]
